services:
  - type: web
    name: brain-tumor-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: AI_CONFIDENCE_THRESHOLD
        value: "0.70"
      - key: AI_UNCERTAINTY_THRESHOLD
        value: "0.025"
